---
- name: Ensure /run/sshd exists for validation
  ansible.builtin.file:
    path: /run/sshd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: SSH Configuration. Turning Off Root Login
  ansible.builtin.copy:
    src: ssh_conf/99-root-block.conf
    dest: /etc/ssh/sshd_config.d/
    mode: '0644'
    owner: root
    group: root
    validate: 'sshd -t -f %s'
  notify: reload-sshd

- when: ssh_keys | default(false) | bool
  block:
    - name: create dir .ssh
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh/"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ admins }}"

    - name: deploy key
      ansible.builtin.copy:
        src: "{{ item.key_path }}"
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0600'
      loop: "{{ admins }}"

    - name: Setup key login
      ansible.builtin.copy:
        src: ssh_conf/98-ssh-keys.conf
        dest: /etc/ssh/sshd_config.d/
        owner: root
        group: root
        mode: '0644'
        validate: 'sshd -t -f %s'
      notify: reload-sshd